name: CI

on:
  pull_request_target:
    branches: [develop, main]
  push:
    branches: ['feature/**']
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test & Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR HEAD
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install deps
        run: npm ci

      - name: Run tests (Jest)
        run: npm test -- --runInBand --coverage

      - name: Upload coverage HTML
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage

      - name: Upload JUnit
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-report
          path: reports/junit/junit.xml

      - name: Summary
        if: always()
        run: |
          echo "## Resultados de Tests" >> $GITHUB_STEP_SUMMARY
          echo "- Cobertura HTML y JUnit adjuntos como artifacts." >> $GITHUB_STEP_SUMMARY
